# Generated by Django 3.2.6 on 2021-08-20 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Мусор',
                'verbose_name_plural': 'Мусор',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('birthday_date', models.DateField(default=datetime.datetime(2021, 8, 20, 7, 44, 43, 114312, tzinfo=utc), verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserGarbage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalCount', models.IntegerField(verbose_name='Количество (x50 гр.)')),
                ('garbageType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.garbagetype', verbose_name='Тип муcора')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user', verbose_name='Обладатель')),
            ],
            options={
                'verbose_name': 'Мусор позьзователя',
                'verbose_name_plural': 'Мусор позьзователя',
            },
        ),
    ]
