# Generated by Django 3.2.6 on 2021-08-20 08:33

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, verbose_name='Код подтверждения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Ключ доступа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 20, 8, 32, 56, 851782, tzinfo=utc), verbose_name='Дата рождения'),
        ),
    ]
