# Generated by Django 3.2.6 on 2021-08-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210820_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday_date',
        ),
    ]
