# Generated by Django 3.2.6 on 2021-08-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_birthday_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergarbage',
            name='garbageType',
        ),
        migrations.RemoveField(
            model_name='usergarbage',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Рядовой пользователь', 'verbose_name_plural': 'Рядовые пользователи'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='garb_aluminum_can',
            field=models.IntegerField(default=0, verbose_name='Алюминиевых банок'),
        ),
        migrations.AddField(
            model_name='user',
            name='garb_cardboard',
            field=models.IntegerField(default=0, verbose_name='Картона'),
        ),
        migrations.AddField(
            model_name='user',
            name='garb_glass',
            field=models.IntegerField(default=0, verbose_name='Стекла'),
        ),
        migrations.AddField(
            model_name='user',
            name='garb_plastic_bottle',
            field=models.IntegerField(default=0, verbose_name='ПЭТ-бутылок'),
        ),
        migrations.AddField(
            model_name='user',
            name='garb_plastic_lid',
            field=models.IntegerField(default=0, verbose_name='Пластиковых крышечек'),
        ),
        migrations.AddField(
            model_name='user',
            name='garb_plastic_mk2',
            field=models.IntegerField(default=0, verbose_name='Пластика маркировки «2»'),
        ),
        migrations.AddField(
            model_name='user',
            name='garb_plastic_mk5',
            field=models.IntegerField(default=0, verbose_name='Пластика маркировки «5»'),
        ),
        migrations.AddField(
            model_name='user',
            name='garb_wastepaper',
            field=models.IntegerField(default=0, verbose_name='Макулатуры'),
        ),
        migrations.DeleteModel(
            name='GarbageType',
        ),
        migrations.DeleteModel(
            name='UserGarbage',
        ),
    ]
