# Generated by Django 3.2.6 on 2021-08-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210820_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_link', models.TextField(verbose_name='Ссылка на иконку')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='Монеты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='garb_aluminum_can',
            field=models.IntegerField(default=0, verbose_name='Алюминиевых банок (x50 гр.)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='garb_cardboard',
            field=models.IntegerField(default=0, verbose_name='Картона (x50 гр.)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='garb_glass',
            field=models.IntegerField(default=0, verbose_name='Стекла (x50 гр.)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='garb_plastic_bottle',
            field=models.IntegerField(default=0, verbose_name='ПЭТ-бутылок (x50 гр.)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='garb_plastic_lid',
            field=models.IntegerField(default=0, verbose_name='Пластиковых крышечек (x50 гр.)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='garb_plastic_mk2',
            field=models.IntegerField(default=0, verbose_name='Пластика маркировки «2» (x50 гр.)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='garb_plastic_mk5',
            field=models.IntegerField(default=0, verbose_name='Пластика маркировки «5» (x50 гр.)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='garb_wastepaper',
            field=models.IntegerField(default=0, verbose_name='Макулатуры (x50 гр.)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Номер телефона'),
        ),
    ]
