# Generated by Django 3.2.6 on 2021-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210820_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=100, verbose_name='Адрес')),
                ('snippet', models.CharField(default='', max_length=50, verbose_name='Режим работы')),
                ('latitude', models.FloatField(default=0, verbose_name='Широта')),
                ('longitude', models.FloatField(default=0, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.AlterModelOptions(
            name='collectionplace',
            options={'verbose_name': 'Место сбора мусора', 'verbose_name_plural': 'Места сбора мусора'},
        ),
        migrations.AddField(
            model_name='collectionplace',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='collectionplace',
            name='latitude',
            field=models.FloatField(default=0, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='collectionplace',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='collectionplace',
            name='snippet',
            field=models.CharField(default='', max_length=50, verbose_name='Режим работы'),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
    ]
