# Generated by Django 3.2.6 on 2021-08-21 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210821_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='QR Ключ доступа'),
            preserve_default=False,
        ),
    ]
